# Generated by Django 2.0 on 2020-12-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgrest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('tenant_id', models.AutoField(primary_key=True, serialize=False)),
                ('db_instance_name', models.CharField(max_length=255)),
                ('tenant_name', models.CharField(max_length=255, unique=True))
            ]
        )
    ]
