# Generated by Django 2.0 on 2021-03-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgrest', '0002_tenants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenants',
            name='db_section',
        ),
        migrations.AddField(
            model_name='tenants',
            name='db_instance_name',
            field=models.CharField(default='local', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenants',
            name='tenant_name',
            field=models.CharField(default='dev', max_length=255),
            preserve_default=False,
        ),
    ]
