# Generated by Django 1.9 on 2015-12-19 10:54
from django.db import migrations, models
from django_tenants.postgresql_backend.base import _check_schema_name
from paas import settings

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('schema_name', models.CharField(unique=True, max_length=63, validators=[_check_schema_name])),
                ('tenant_id', models.AutoField(serialize=False, auto_created=True, primary_key=True)),
                ('tenant_name', models.CharField(max_length=255, unique=True)),
                ('db_instance_name', models.CharField(max_length=255))
            ]
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=253, unique=True, db_index=True)),
                ('is_primary', models.BooleanField(default=True, db_index=True)),
                ('tenant', models.ForeignKey(settings.TENANT_MODEL, db_index=True, related_name='domains', on_delete=models.CASCADE))
            ]
        )
    ]
